// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lookup_user_and_hash.sql

package database

import (
	"context"
	"database/sql"
)

const userandHashLookup = `-- name: UserandHashLookup :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE email=$1
`

func (q *Queries) UserandHashLookup(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, userandHashLookup, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
