// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_email_and_password.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateEmailAndPassword = `-- name: UpdateEmailAndPassword :exec
UPDATE users SET email=$1, hashed_password=$2,updated_at=NOW() WHERE id=$3
`

type UpdateEmailAndPasswordParams struct {
	Email          sql.NullString
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateEmailAndPassword(ctx context.Context, arg UpdateEmailAndPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailAndPassword, arg.Email, arg.HashedPassword, arg.ID)
	return err
}
