// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: upgrade_to_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeToChirpyRed = `-- name: UpgradeToChirpyRed :exec
UPDATE users SET is_chirpy_red='true' WHERE id=$1
`

func (q *Queries) UpgradeToChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeToChirpyRed, id)
	return err
}
